### ISSUE TITLE
Redis exporter doesn't expose redis-cli info to prometheus

### ISSUE THREAD

**Issue by ealebed** [oliver006/redis_exporter#104]
Hi, I need you advice.

I want to expose redis-cli info to /metrics in redis exporter so the grafana dashboard can collect them.

My docker-compose file looks like:
```
version: '3'
services:
......(another services)
  redis:
    container_name: redis
    image: registry.gitlab.lc:5000/develop/ed/redis-ed-sq:latest
    volumes:
      - redis:/data
    ports:
      - "6379:6379"
    logging:
      driver: gelf
      options:
        gelf-address: "udp://${GRAYLOG_ADDR}:12201"
        tag: "redis"
.....(another services)

  devredisexporter:
    image: oliver006/redis_exporter:v0.12.2
    container_name: devredisexporter
    restart: unless-stopped
    ports:
      - 9121:9121
    entrypoint: /bin/redis_exporter -redis.addr redis://redis:6379 -redis.password 'myPass'
    labels:
      org.label-schema.group: "monitoring"
.......
```

I also tried this:
```
  devredisexporter:
    image: oliver006/redis_exporter:v0.12.2
    container_name: devredisexporter
    command:
      - '-redis.password=myPass'
      - '-redis.addr=redis://redis:6379'
    restart: unless-stopped
    ports:
      - 9121:9121
    labels:
      org.label-schema.group: "monitoring"
```
And tried run redis_exporter in container on separate host (in this case I use -redis.addr=redis://192.168.0.20:6379) - same result:

```
# docker logs -f devredisexporter
time="2017-09-22T07:39:14Z" level=info msg="Redis Metrics Exporter v0.12.2    build date: 2017-09-03-02:33:43    sha1: 01ace8c5ffded06c5484fd52334e333a5235e4c4    Go: go1.8.3\n" 
time="2017-09-22T07:39:14Z" level=info msg="Providing metrics at :9121/metrics" 
time="2017-09-22T07:39:14Z" level=info msg="Connecting to redis hosts: []string{\"redis://redis:6379\"}" 
time="2017-09-22T07:39:14Z" level=info msg="Using alias: []string{\"\"}" 

time="2017-09-22T07:39:25Z" level=info msg="redis err: dial redis: unknown network redis"
```
Web interface runned (http://192.168.0.20:9121/metrics), but about redis there are only this strings:
```
# HELP redis_exporter_build_info redis exporter build_info
# TYPE redis_exporter_build_info gauge
redis_exporter_build_info{build_date="2017-09-03-02:33:43",commit_sha="01ace8c5ffded06c5484fd52334e333a5235e4c4",golang_version="go1.8.3",version="v0.12.2"} 1
# HELP redis_exporter_last_scrape_duration_seconds The last scrape duration.
# TYPE redis_exporter_last_scrape_duration_seconds gauge
redis_exporter_last_scrape_duration_seconds 0.00177992
# HELP redis_exporter_last_scrape_error The last scrape error status.
# TYPE redis_exporter_last_scrape_error gauge
redis_exporter_last_scrape_error 1
# HELP redis_exporter_scrapes_total Current total redis scrapes.
# TYPE redis_exporter_scrapes_total counter
redis_exporter_scrapes_total 1
# HELP redis_up 
# TYPE redis_up gauge
redis_up{addr="redis://redis:6379",alias=""} 0
```

I can ping redis from container devredisexporter:
```
# ping redis
PING redis (172.25.0.11): 56 data bytes
64 bytes from 172.25.0.11: seq=0 ttl=64 time=0.087 ms
64 bytes from 172.25.0.11: seq=1 ttl=64 time=0.110 ms
```

Docker Version:
```
Client:
 Version:      17.06.1-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:51:12 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.1-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:50:04 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

docker-compose  version 
```
docker-compose version 1.14.0, build c7bdf9e
docker-py version: 2.3.0
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
```

Full docker info (Swarm mode active):
```
docker info
Containers: 13
 Running: 11
 Paused: 0
 Stopped: 2
Images: 394
Server Version: 17.06.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 405
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: udow4edogefqxcfs6gzkkgh6w
 Is Manager: true
 ClusterID: ut8uvfxdk1ldgguazc7snuc6u
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Root Rotation In Progress: false
 Node Address: 192.168.0.34
 Manager Addresses:
  192.168.0.34:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-93-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.67GiB
Name: e-lebed.lc
ID: 7VNW:YUXN:EOH2:3JRQ:V7AX:O5OQ:EYJ3:UT7H:JNM3:SGTK:BRIP:DHKB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: ealebed
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```
Can you help me?
