### ISSUE TITLE
Redis exporter cluster on Kubernetes  

### ISSUE THREAD

**Issue by LuisMLGDev** [oliver006/redis_exporter#190]
Hi guys,
I deployed redis_exporter on my redis_cluster (4 redis pods) which is over K8s. It´s working but now I just got metrics from 1 node of the cluster. 
I configured the scrape as a static one:

```
- job_name: "redis-cluster"
  metrics_path: /metrics
  static_configs:
  - targets: ["redis-cluster.db.svc.cluster.local:9121"]
```

Of course the redis-cluster.db.svc.cluster.local is the service for redis...
I also tried using the SD like this:
```
- job_name: redis
  honor_labels: true
  scrape_interval: 30s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  kubernetes_sd_configs:
  - api_server: null
    role: pod
    namespaces:
      names:
      - db
  tls_config:
    insecure_skip_verify: true
  relabel_configs:
  - source_labels: [__meta_kubernetes_pod_container_port_number]
    separator: ;
    regex: 9121
    target_label: pod
    replacement: $1
    action: keep
```
The SD didn´t discover anything ... no new targets were added :(
So what you think guys is the best approach to get that in grafana dashboard, just adding a new variable, I will be able to choose among all redis pods.
