### ISSUE TITLE
Support port with docker env var

### ISSUE THREAD

**Issue by perfectacle** [oliver006/redis_exporter#262]
I try to access a multiple Redis instance running on the host node
and I try to use multiple redis_exporter using docker
(because I can't want to install go or other dependency, so I have to use host network mode)

but redis_exporter docker isn't support port flag.
So, I can't use multiple redis_exporter using docker in host network mode.

Please support it!

**Comment by oliver006** [comment]
You can supply a port to redis_exporter as part of the redis URI:

`redis://hostname:port`

This also works when scraping multiple instances as explained in the documentation [here](https://github.com/oliver006/redis_exporter#prometheus-configuration-to-scrape-several-hosts).

**Comment by perfectacle** [comment]
Instead of writing down the address of the redis, we are detecting the service by consul in case of a dynamic increasing instance of the redis and letting it be automatically added.
My settings are as follows.
```
- job_name: 'redis_exporter'
  consul_sd_configs:
    - server: 'http://consul-001.dns:8500'
    - server: 'http://consul-002.dns:8500'
    - server: 'http://consul-003.dns:8500'
  relabel_configs:
    - source_labels: [__meta_consul_tags]
      regex: .*,redis_exporter,.*
      action: keep
```

Therefore, I hope to support receiving the port as an option.

**Comment by oliver006** [comment]
Thanks for the additional information @perfectacle 

I'm not sure I understand how your snippet above translates into how the redis_exporters are discovered and scraped.
Does Consul return the addresses of the redis_exporters? Do you run a redis exporter per redis instance? How do you run redis_exporter (full command line with flags)?

**Comment by perfectacle** [comment]
I installed redis(on host os), redis-exporter(on docker), consul(on docker, client mode) on same host.

consul client have to register service to consul server.
so this is example.
```json5
{
  "services": [
    {
      "id": "Thumbor Redis Exporter", // thumbor is a tool for creating image thumbnails.
      "name": "thumbor-redis",
      "port": 9121,
      "tags": [ // It is used to filter indicators in Prometheus
        "redis_exporter"
      ],
      "meta": { // the meta information are for grafana
        "application": "thumbor-redis",
        "port": "6379"
      },
      "check": {
        "id": "Thumbor Redis Exporter Health Check",
        "name": "Thumbor Redis Exporter Status",
        "tcp": "localhost:9121",
        "interval": "10s",
        "timeout": "1s"
      }
    }
  ]
}
```

When I visited consul server UI, I can see redis exporter service and **redis_exporter** tag.
![Screen Shot 2019-06-02 at 10 48 26 AM](https://user-images.githubusercontent.com/15857795/58755724-79c85600-8524-11e9-9eaa-e06dcb6cba63.png)

Prometheus scrape config
```yml
scrape_configs:
  - job_name: 'redis_exporter'
    consul_sd_configs:
      # Describe the list of consul servers.
      - server: 'http://consul-001.dns:8500'
      - server: 'http://consul-002.dns:8500'
      - server: 'http://consul-003.dns:8500'
  relabel_configs:
    # filtering by consul tag name
    - source_labels: [__meta_consul_tags]
      regex: .*,redis_exporter,.*
      action: keep
    # below labels are for grafana
    - source_labels: [__meta_consul_service_metadata_application]
      target_label: 'application'
    - source_labels: [__meta_consul_address]
      target_label: 'ip'
    - source_labels: [__meta_consul_service_metadata_port]
      target_label: 'port'
```

When I visited grafana, I can see it. (I customized your exporter's variable configuration)
![image](https://user-images.githubusercontent.com/15857795/58755818-dc225600-8526-11e9-9ece-d2da8e877080.png)

If you have something to create a new redis, you only need to set up a new Exporter and Consul on the host or modify the consul config file.
As a result, you don't have to touch it at all at Prometheus.
