### ISSUE TITLE
How to scrape metrics form a redis cluster

### ISSUE THREAD

**Issue by KyleRicardo** [oliver006/redis_exporter#281]
I am using the command line
```
./redis_exporter --redis.addr="redis://192.168.1.131:7001,redis://192.168.1.131:7002,redis://192.168.1.131:7003,redis://192.168.1.131:7004,redis://192.168.1.131:7005,redis://192.168.1.131:7006"
```
but I got this error message
```
redis_exporter_last_scrape_error{err="dial tcp: address redis://192.168.1.131:7001,redis://192.168.1.131:7002,redis://192.168.1.131:7003,redis://192.168.1.131:7004,redis://192.168.1.131:7005,redis://192.1681.131:7006: too many colons in address"} 1
```
when I visit `http://192.168.1.131:9121/metrics` directly in browser.

When I change the command line to include just one node like this
```
./redis_exporter --redis.addr="redis://192.168.1.131:7001"
```
it works fine but then Grafana has only one instance option to select. I doubt this is the right way to use this exporter.

So how can I scrape the cluster metrics by letting the exporter to connect all these nodes?

Also, I found that the variable in Grafana is named of "addr", but it did't work. Promethues showed that there was only one instance up. And the port is 9121, the exporter itself. So I can only use the variable name "instance" rather than "addr" to get Grafana Board worked. I'm so confused here. Shouldn't I select the addr of redis nodes rather than the exporter?

If needed, I can explain more details.

Thanks for your generous working!

**Comment by oliver006** [comment]
Have a look here: [how to configure the exporter when scraping multiple instances.](https://github.com/oliver006/redis_exporter#prometheus-configuration-to-scrape-multiple-redis-hosts)

**Comment by oliver006** [comment]
And you'll need to adjust your Grafana dashboard to not use the `addr` variable any longer but use `instance`.

**Comment by KyleRicardo** [comment]
Before I submited this issue, I have read the README.md in detail and I wrote the `prometheus.yml` file exactly as your guide said. That's ok and it actually worked. I'm just confused how to run the redis_exporter with the proper `redis.addr` param. In the README.md I couldn't find how to populate this param when it came to more than one node. Should I put just one node in that param randomly or all the nodes in it? If all nodes should be put in, then what's the illegal format for this param to avoid the `to manmy colons in address` error?

Plz forgive my stupidity.

**Comment by oliver006** [comment]
See the first paragraph here: https://github.com/oliver006/redis_exporter#prometheus-configuration-to-scrape-multiple-redis-hosts

> Run the exporter with the command line flag `--redis.addr=`

That should take care of the issue you're having.

**Comment by KyleRicardo** [comment]
I have read that paragraph, and let me express my confusion in another way.

I now have 6 nodes in one physical machine (or rather, one virtual machine in VMWare Workstation), they are:

```
redis://192.168.1.131:7001 (Master)
redis://192.168.1.131:7002 (Master)
redis://192.168.1.131:7003 (Master)
redis://192.168.1.131:7004 (Slave)
redis://192.168.1.131:7005 (Slave)
redis://192.168.1.131:7006 (Slave)
```

Cluster has been established.

And here's the problem:

When I use redis_exporter, should I use (`too many colons in address` error will occur because I don't know the **RIGHT** format)
**A**
```
./redis_exporter --redis.addr="redis://192.168.1.131:7001,redis://192.168.1.131:7002,redis://192.168.1.131:7003,redis://192.168.1.131:7004,redis://192.168.1.131:7005,redis://192.168.1.131:7006"
```
or (this works fine)
**B**
```
./redis_exporter --redis.addr="redis://192.168.1.131:7001"
```
is just enough?

**A** or **B**？

If **A**, then what's the **RIGHT** format of the `redis.addr` param when I have mutiple nodes?

If **B**, then I understand and there will be no problem at all.

**Comment by oliver006** [comment]
Run your exporter like this: `./redis_exporter --redis.addr=` (yes, just an empty string for --redis.addr)

and the prometheus.yml file should list the hosts you're trying to scrape, looking something like this: 

```
scrape_configs:
  ## config for the multiple Redis targets that the exporter will scrape
  - job_name: 'redis_exporter_targets'
    static_configs:
      - targets:
        - redis://192.168.1.131:7001
        - redis://192.168.1.131:7002
        - redis://192.168.1.131:7003
        - redis://192.168.1.131:7004
        - redis://192.168.1.131:7005
        - redis://192.168.1.131:7006
    metrics_path: /scrape
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: <<REDIS-EXPORTER-HOSTNAME>>:9121
```
