### ISSUE TITLE
/scrape ignore REDIS_EXPORTER_CHECK_KEYS / --check-keys

### ISSUE THREAD

**Issue by zhil** [oliver006/redis_exporter#282]
**Describe the problem**
I am storing application metrics in redis like 
metrics:1:counter
metrics:2:counter
etc

And I use parameter --check-keys=metrics:*
Unfortunately, its not working any more for "/scrape mode" (like localhost:9121/scrape?target=sometarget). Works fine for "/metrics mode" (like  localhost:9121/metrics).

Also I tried MONITOR command and exporter even didnt try to SCAN keys (only INFO ALL command is send from exporter)

**What version of redis_exporter are you running?**
I am using 1.x branch via docker.
Not sure about exact version, because I get weird output
```
docker exec -it redisexporter sh
redis_exporter --version
```
got output
```
INFO[0000] Redis Metrics Exporter <<< filled in by build >>>    build date: <<< filled in by build >>>    sha1: <<< filled in by build >>>    Go: go1.10.8 
DEBU[0000] Enabling debug output      
```

**Running the exporter**
I am using docker-compose
Dockerfile
```
#
# build container
#
FROM golang:1.10
WORKDIR /go/src/github.com/oliver006/

RUN git clone https://github.com/oliver006/redis_exporter.git

ARG SHA1
ENV SHA1=$SHA1
ARG TAG
ENV TAG=$TAG
ARG DATE
ENV DATE=$DATE

RUN cd /go/src/github.com/oliver006/redis_exporter/ && CGO_ENABLED=0 GOOS=linux go build -ldflags  " -X main.VERSION=$TAG -X main.COMMIT_SHA1=$SHA1 -X main.BUILD_DATE=$DATE " -a -installsuffix cgo -o redis_exporter .


#
# release container
#
FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /bin/
COPY --from=0 /go/src/github.com/oliver006/redis_exporter/ .

EXPOSE     9121
ENTRYPOINT [ "/bin/redis_exporter", "--check-keys=metrics:*" , "--redis.addr=" ]
```

**Expected behavior**
--check-keys is not working for "/scrape", working only for "/metrics"

**Screenshots**
-

**Additional context**
-

**Comment by oliver006** [comment]
Ah yes, this isn't working correctly and/or not documented at all, thanks for raising this issue !

The way it's set up to work right now is to use a `check-keys` parameter as part of the prometheus.yml config:

```
scrape_configs:
  ## config for the multiple Redis targets that the exporter will scrape
  - job_name: 'redis_exporter_targets'
    static_configs:
      - targets:
        - redis://first-redis-host:6379
        - redis://second-redis-host:6379
    metrics_path: /scrape
    params:
      check-keys: "metrics:*"

...
```

which is then picked up [here](https://github.com/oliver006/redis_exporter/blob/master/exporter.go#L84).

That's neither very intuitive nor documented nor very convenient.
To address your immediate problem, can you try using the `params` block as in the config above?

I'll think of a better way to configure this or at least add a section to the docs that explain this.
