### ISSUE TITLE
metrics redis_memory_max_bytes always return 0

### ISSUE THREAD

**Issue by ganpengyu** [oliver006/redis_exporter#300]
**Describe the problem**

metrics redis_memory_max_bytes always return 0, so that grafana calculate 

```
100 * (redis_memory_used_bytes{instance=~"$instance"}  / redis_memory_max_bytes{instance=~"$instance"})
```

always return N/A

**What version of redis_exporter are you running?**
[ ] 0.3x.x
[✔️ ] 1.x.x

**Running the exporter**

nohup ./redis_exporter > startup.log 2>&1 &

**Expected behavior**

redis_memory_max_bytes return true value

**Additional context**

My config as below

discovery.json

```
[
    {
        "targets": [
            "redis://172.16.0.239:6301",
            "redis://172.16.0.239:6302",
            "redis://172.16.0.239:6303",
            "redis://172.16.0.239:26301",
            "redis://172.16.0.239:26302",
            "redis://172.16.0.239:26303"
        ],
        "labels": {
            "team": "mro",
            "component": "redis",
            "env": "qa"
        }
    }
]
```

prometheus.yml

```
# Redis Servers
  - job_name: 'qa-redis'
    file_sd_configs:
      - files:
        - discovery.json
    metrics_path: /scrape
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 172.16.0.239:9121
```
