### ISSUE TITLE
prometheus did not collect metrics from redis_exported

### ISSUE THREAD

**Issue by KePeng1019** [oliver006/redis_exporter#353]
i follow readme and start redis_exporter with command
```shell
./redis_exporter --redis.addr=172.17.28.208:6656
```
and got log
```
Providing metrics at :9121/metrics
```
then i have prometheus with config:
```yaml
- job_name: 'redis_exporter'
    static_configs:
      - targets: ['172.17.28.154:9121']
```
every thing seems ok but prometheus did not collect metrics and redis_exporter did not have any log.
please help.
