### ISSUE TITLE
Unable to connect using target with password in URI

### ISSUE THREAD

**Issue by wolmi** [oliver006/redis_exporter#364]
This is my environment:

**docker-compose.yaml**
```yaml
version: "3"
services:
  redis-exporter:
    image:  oliver006/redis_exporter:v1.5.0
    environment:
      - REDIS_ADDR=""
      - REDIS_EXPORTER_INCL_SYSTEM_METRICS=true
      - REDIS_EXPORTER_SET_CLIENT_NAME=false
      - REDIS_EXPORTER_DEBUG=true
    ports:
      - 9121:9121
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./grafana-storage:/var/lib/grafana
      - ./grafana/config.ini:/etc/grafana/config.ini
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - 3000:3000
```
**prometheus.yaml**
```yaml
# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'codelab-monitor'

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first.rules"
  # - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  ## config for the multiple Redis targets that the exporter will scrape
  - job_name: 'redis_exporter_targets'
    static_configs:
      - targets:
        - redis://h:****************@redis-******.c1.us-east1-2.gce.cloud.redislabs.com:******
    metrics_path: /scrape
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: redis-exporter:9121
      - source_labels: [instance]
        regex: '(.*:\/\/).*:([0-9a-zA-Z].*)@(.*)'
        replacement: '$1$3'
        target_label: instance
  - job_name: 'redis_exporter'
    static_configs:
      - targets:
        - redis-exporter:9121
```

With that configuration, I have always the error:

`err: NOAUTH Authentication required`

and the `Trying DialURL()` debug message show the URI without credentials.
I see on the exporter.go that the User is removed from the target when it is set from the parameter.

https://github.com/oliver006/redis_exporter/blob/7767367a3bff56e1d4c28bb9eeda1c3d7d2a5098/exporter.go#L92

But It works if the password is set as an environment variable, as per the README I undersdtand that I can use the URI with user:password but it doen't work.

Removing the Line 92 solves the problem
