### ISSUE TITLE
Can this support redis-cluster monitor?

### ISSUE THREAD

**Issue by wavelet123** [oliver006/redis_exporter#368]
Hi,
Just want to confirm whether this tool support redis-cluster monitoring?

Thanks,
Xiao Peng

**Comment by bruce-sha** [comment]
+1

**Comment by oliver006** [comment]
Yes, the exporter supports extracting metrics related to clustering. You'll have to make sure you scrape all instances of your cluster.

**Comment by ehassan1312** [comment]
Hi Oliver
How to scrape all instances ? should I configure the exporter on each instance ? I tried to configure it on a single node and  append list of redis cluster's IPs "-redis.addr=x.x.x.x:6379,x.x.x.x:6380 " , but it gave me error 'too many colons in address" .

thanks in advance

**Comment by oliver006** [comment]
Yes, you need to scrape instances individually.
Have a look at the README how to configure Prometheus and the exporter, in particular this section: https://github.com/oliver006/redis_exporter#prometheus-configuration-to-scrape-multiple-redis-hosts

**Comment by ehassan1312** [comment]
ok, I  configured the exporter on each instance , but I didn't know how to configure the prometheus
in README you just wrote one IP for exporter .
I didn't get what you mean in this part:

relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: <<REDIS-EXPORTER-HOSTNAME>>:9121     // should here write all instances?

**Comment by oliver006** [comment]
You shouldn't have to change any f that, just the
`replacement: <<REDIS-EXPORTER-HOSTNAME>>:9121`
part and point it at your redis exporter.

**Comment by bruce-sha** [comment]
I was confused  too. for 6  redis instance in  one redis-cluster , I need to run one redis_exporter or six?

**Comment by oliver006** [comment]
You need to scrape every single redis instance, there are two way to do this:
- run an exporter per redis instance (e.g. on the same box, depends on your setup)
- have one exporter scrape all six cluster instances (see link [here](https://github.com/oliver006/redis_exporter/issues/368#issuecomment-603848029) for how to do this)

**Comment by ehassan1312** [comment]
sorry Oliver , but my cluster installed on VMs not kubernetes or containers.
so I can't imagine how to configure that .
my cluster consists of  3 nodes . each node has 2 processes one master running on port:6379 and another one slave running on  port:6380.
in this case ,should I configure 6 exporter for each process ? and in this case how to configure that on prometheus perspective ?

**Comment by oliver006** [comment]
You can put a redis exporter on each of your VMs that runs redis. In your case it'd be two exporter per VM instance (one for the redis master, one for the redis slave) and then your Prometheus server would use whatever Service Discovery (SD) mechanism you have and use it to discover and scrape those exporters.

OR.

You run one exporter in a central place and again use whatever SD you have and scrape all redis instances directly.

**Comment by ehassan1312** [comment]
Many Thanks Oliver . I tried the second solution and it's working fine .

**Comment by keepwalking86** [comment]
> sorry Oliver , but my cluster installed on VMs not kubernetes or containers.
> so I can't imagine how to configure that .
> my cluster consists of 3 nodes . each node has 2 processes one master running on port:6379 and another one slave running on port:6380.
> in this case ,should I configure 6 exporter for each process ? and in this case how to configure that on prometheus perspective ?

Reference this section: https://github.com/oliver006/redis_exporter#prometheus-configuration-to-scrape-multiple-redis-hosts
The following configuration:
Redis_exporter (192.168.1.111)
Redis instances: 192.168.1.112:30001,192.168.1.112:30002,192.168.1.113:30001,192.168.1.113:30002,192.168.1.114:30001,192.168.1.114:30002

## Step1: Setup redis_exporter

Setup redis_exporter on prometheus (192.168.1.111)

```
cat >/etc/systemd/system/redis_exporter.service<<EOF
[Unit]
Description=Redis Exporter
Documentation=https://github.com/oliver006/redis_exporter
Wants=network-online.target
After=network-online.target

[Service]
Type=simple
User=prometheus
Group=prometheus
ExecReload=/bin/kill -HUP \$MAINPID
ExecStart=/usr/bin/redis_exporter \
  --log-format=txt \
  --namespace=redis \
  --web.listen-address=:9121 \
  --web.telemetry-path=/metrics \
  --redis.addr=

SyslogIdentifier=redis_exporter
Restart=always

[Install]
WantedBy=multi-user.target
EOF
```
## Step2: Configure prometheus

```
  #Redis Exporter
  - job_name: redis_exporter
    static_configs:
      - targets: ['192.168.1.111:9121']
  - job_name: 'redis_exporter_targets'
    static_configs:
      - targets:
        - redis://192.168.1.112:30001
        - redis://192.168.1.112:30002
        - redis://192.168.1.113:30001
        - redis://192.168.1.113:30002
        - redis://192.168.1.114:30001
        - redis://192.168.1.114:30002
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.1.111:9121
```
