### ISSUE TITLE
Multi Cluster Monitoring Clarification

### ISSUE THREAD

**Issue by rjshrjndrn** [oliver006/redis_exporter#385]
**Describe the problem**
1. Created 2  redis instances
2. Installed stable/redis exporter
    `helm install stable/redis-exporter`
3. Created prometheus-operator with `additional scrape configs`
```
    additionalScrapeConfigs:
      - job_name: 'redis_exporter'
        metrics_path: /metrics
        static_configs:
        - targets:
          - redis-1-headless:6379
          - redis-2-headless:6379
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: redis-exporter:9121
```
4. Added grafana dashboard(763 id)

Not able to see multiple redis instances metrics

**What version of redis_exporter are you running?**
Please run `redis_exporter --version` if you're not sure what version you're running.
[ x ] 1.x.x

**Running the exporter**
What's the full command you're using to run the exporter? (please remove passwords and other sensitive data)
Please include details about env variables, command line parameters, your orchestration setup, etc.

no arguments

Am I missing something, I read in the issues that new design is like blackbox exporter. But in that case, why am I not getting any metrics fro the servers.

**Comment by rjshrjndrn** [comment]
Closing as this was a configuration issue.
For future debuggers, below is the additionalScrapeConfig for prometheus-operator
```
    additionalScrapeConfigs:
      - job_name: 'redis_exporter'
        metrics_path: /metrics
        static_configs:
        - targets:
          - redis://redis-1-headless:6379
          - redis://redis-2-headless:6379
        metrics_path: /scrape
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: redis-exporter:9121
```
