### ISSUE TITLE
how to use the exporter to show sentinel info

### ISSUE THREAD

**Issue by ariefMudahMy** [oliver006/redis_exporter#429]
**Describe the problem**
Hi, i have 3 redis nodes and sentinel
this is my for docker-compose.yaml config
```
- job_name: 'redis-exporter-targets'
    static_configs:
      - targets:
        - redis://xx.xx.xx.xx:6379
        - redis://yy.yy.yy.yy:6379
        - redis://zz.zz.zz.zz:6379
    metrics_path: /scrape
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement:  redis-exporter:9121
  - job_name: 'redis-exporter'
    static_configs:
      - targets:
        - redis-exporter:9121
```
my redis-sentinel is running in each of redis node at port 26379

how to make prometheus show. sentinel metrics?

**What version of redis_exporter are you running?**
v.1.12.0

**Comment by oliver006** [comment]
Try adding the sentinels to your list of targets:

```
- job_name: 'redis-exporter-targets'
    static_configs:
      - targets:
        - redis://xx.xx.xx.xx:6379
        - redis://yy.yy.yy.yy:6379
        - redis://zz.zz.zz.zz:6379
        - redis://xx.xx.xx.xx:26379
        - redis://yy.yy.yy.yy:26379
        - redis://zz.zz.zz.zz:26379
```
