### ISSUE TITLE
Promentheus operator and redis exporter without side-car

### ISSUE THREAD

**Issue by pmmalinov01** [oliver006/redis_exporter#432]
**Describe the problem**
I have a Redis cluster and Redis-exporter in two separate deployments in the same namespace of a Kubernetes cluster. I am using Prometheus operator to monitor the cluster, but I can not find a way to set up the exporter and the operator. I have set up a service targeting the redis exporter(check below) and a ServiceMonitor(also below)

**What version of redis_exporter are you running?**
Please run `redis_exporter --version` if you're not sure what version you're running.
[ ] 0.3x.x
[x] 1.x.x

**Running the exporter**

```
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: bi-infra
  name: redis-exporter
  labels:
    app: redis-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-exporter
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9122"
      labels:
        app: redis-exporter
    spec:
      containers:
      - name: redis-exporter
        image: oliver006/redis_exporter:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: REDIS_ADDR
          value:  redis-cluster.bi-infra.svc:6379
        ports:
        - containerPort: 9121
```

**Additional context**
```apiVersion: v1
kind: Service
metadata:
  name: redis-external-exporter
  namespace: bi-infra
  labels:
    app: redis
    k8s-app: redis-ext
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: "9122"
spec:
  ports:
  - name: redis-ext
    port: 9122
    protocol: TCP
    targetPort: 9121
  selector:
    app: redis-exporter
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-external-exporter
  namespace: bi-infra
  labels:
    app: redis-external-exporter
    k8s-app: redis-monitor
spec:
  jobLabel: app
  selector:
    matchLabels:
      app: redis-ext
  namespaceSelector:
    matchNames:
    - bi-infra
  endpoints:
  - port: redis-ext
    interval: 30s
    honorLabels: true
```

If this is not related to redis-exporter, you can close it.
