### ISSUE TITLE
Should check-single-keys/check-keys report 0 for non-existent key?

### ISSUE THREAD

**Issue by tomasgareau** [oliver006/redis_exporter#479]
**Describe the problem**
I'm currently using redis as a work queue, and I'd like to use `redis_exporter` to give me the current number of items in the queue (of type `list`).

When there are items in the list, this works great and I get the metric: `redis_key_size` (woohoo). However, when this value drops to 0, the metric is missing altogether and Prometheus tells me "no data" rather than "0" items. 

My understanding is that Prometheus [suggests exporting a default value of 0](https://prometheus.io/docs/practices/instrumentation/#avoid-missing-metrics) when you have a time series you know should exist in advance. They also mention however that "most Prometheus client libraries (including Go, Java, and Python) will automatically export a 0 for you" so not sure if this is supposed to be handled by the prometheus client library or what.

I'm fairly new to Go/Prometheus but I'd expect the change would be to modify exporter.go:extractCheckKeyMetrics
```go
if err != nil {
	switch err {
	case errNotFound:
		log.Debugf("Key '%s' not found when trying to get type and size.", k.key)
	default:
		log.Error(err)
	}
	continue
}
```
to call registerConstMetricGauge on `errNotFound`:
```go
if err != nil {
	switch err {
	case errNotFound:
		log.Debugf("Key '%s' not found when trying to get type and size. Exporting 0 by default.", k.key)
		e.registerConstMetricGauge(ch, "key_size", 0, dbLabel, k.key)
	default:
		log.Error(err)
	}
	continue
}
```

I can work around this in PromQL by querying `redis_key_size{key="myqueue"} or vector(0)` but would love to hear your thoughts on this.

**What version of redis_exporter are you running?**
Please run `redis_exporter --version` if you're not sure what version you're running.
[ ] 0.3x.x
[x] 1.x.x

**Running the exporter**
(As part of bitnami/redis helm chart):

```yaml
image:
  registry: docker.io
  repository: bitnami/redis-exporter
  tag: 1.15.1-debian-10-r2
  pullPolicy: IfNotPresent
    
  ## Extra arguments for Metrics exporter
extraArgs:
  check-single-keys: myqueue
  debug: "true"
```
