### ISSUE TITLE
Monitor redis cluster with password authentication does'nt working

### ISSUE THREAD

**Issue by tuananh170489** [oliver006/redis_exporter#494]
**Describe the problem**
I have encountered a problem with redis cluster and password authentication.
My redis cluster with 6 nodes and enabled `requirepass` option
This is my `redis-exporter` manifest
```yaml
apiVersion: v1
kind: Service
metadata:
  name: redis-exporter
  labels:
    app.kubernetes.io/name: redis-exporter
spec:
  ports:
  - name: exporter
    port: 9121
    protocol: TCP
  selector:
    app.kubernetes.io/name: redis-exporter
  type: ClusterIP
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-exporter
  labels:
    app.kubernetes.io/name: redis-exporter
type: Opaque
stringData:
  password: <my-redis-cluster-password>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: redis-exporter
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9121"
      labels:
        app.kubernetes.io/name: redis-exporter
    spec:
      containers:
      - image: oliver006/redis_exporter:alpine
        imagePullPolicy: IfNotPresent
        name: redis-exporter
        args:
          - --web.listen-address=:9121
          - --web.telemetry-path=/metrics
          - --redis.addr=
          - --log-format=txt
          - --namespace=redis
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-exporter
              key: password
        ports:
        - containerPort: 9121
          name: exporter
```
and I have followed the guide https://github.com/oliver006/redis_exporter#prometheus-configuration-to-scrape-multiple-redis-hosts
But `redis-exporter` do not scape metrics from 6 redis nodes, it's only scape from exporter itself.
This is logs of `redis-exporter`:
```
time="2021-02-25T11:16:44+07:00" level=info msg="Redis Metrics Exporter v1.17.1    build date: 2021-02-20-13:14:47    sha1: 39f8ddd5c6bd6e8a14f37779e4899aa884d8a201    Go: go1.16    GOOS: linux    GOARCH: amd64"
time="2021-02-25T11:16:44+07:00" level=debug msg="Enabling debug output"
time="2021-02-25T11:16:44+07:00" level=debug msg="NewRedisExporter options: exporter.Options{User:\"\", Password:\"<my-redis-cluster-password>\", Namespace:\"redis\", PasswordMap:map[string]string{}, ConfigCommandName:\"CONFIG\", CheckSingleKeys:\"\", CheckStreams:\"\", CheckSingleStreams:\"\", CheckKeys:\"\", CheckKeyGroups:\"\", CheckKeyGroupsBatchSize:10000, MaxDistinctKeyGroups:100, CountKeys:\"\", LuaScript:[]uint8(nil), ClientCertificates:[]tls.Certificate(nil), CaCertificates:(*x509.CertPool)(nil), InclSystemMetrics:false, SkipTLSVerification:false, SetClientName:true, IsTile38:false, ExportClientList:false, ExportClientsInclPort:false, ConnectionTimeouts:15000000000, MetricsPath:\"/metrics\", RedisMetricsOnly:false, PingOnConnect:true, Registry:(*prometheus.Registry)(0xc0000767d0), BuildInfo:exporter.BuildInfo{Version:\"v1.17.1\", CommitSha:\"39f8ddd5c6bd6e8a14f37779e4899aa884d8a201\", Date:\"2021-02-20-13:14:47\"}}"
time="2021-02-25T11:16:44+07:00" level=debug msg="keys: []exporter.dbKeyPair(nil)"
time="2021-02-25T11:16:44+07:00" level=debug msg="singleKeys: []exporter.dbKeyPair(nil)"
time="2021-02-25T11:16:44+07:00" level=debug msg="streams: []exporter.dbKeyPair(nil)"
time="2021-02-25T11:16:44+07:00" level=debug msg="singleStreams: []exporter.dbKeyPair(nil)"
time="2021-02-25T11:16:44+07:00" level=debug msg="countKeys: []exporter.dbKeyPair(nil)"
time="2021-02-25T11:16:44+07:00" level=info msg="Providing metrics at :9121/metrics"
time="2021-02-25T11:16:44+07:00" level=debug msg="Configured redis addr: \"\""
```
So, am I missing any steps?
Need your help, thank you!
