### ISSUE TITLE
Multiple Redis servers and -check-key option.

### ISSUE THREAD

**Issue by dragonsmith** [oliver006/redis_exporter#51]
Hello, @oliver006 !

Thank you for you exporter! We are currently relying on it in our installation.

I've found out a strange behavior. Not sure if it is a feature or a bug.

We have multiple Redis servers and one redis-exporter that scrapes them all.
I want to make a designated key from each Redis to be visible to Prometheus. I've added `-check-keys` option. But it only shows the value from one server which it scrapes last.

Here is how to quickly reproduce the problem:

docker-compose.yml
```yaml
services:
  redis1:
    image: redis:3.2.7
    container_name: redis1
    expose:
      - 6379
  redis2:
    image: redis:3.2.7
    container_name: redis2
    expose:
      - 6379
  redisexporter:
    container_name: redis_exporter
    image: oliver006/redis_exporter
    command:
      - '-check-keys=testkey'
      - '-redis.addr=redis://redis1:6379,redis://redis2:6379'
    expose:
      - 9121
    ports:
      - 127.0.0.1:9121:9121
```

Commands:
```shell
docker-compose -f docker-compose.yml up -d
docker exec -it redis1 redis-cli set testkey 1111
docker exec -it redis2 redis-cli set testkey 2222
curl -s localhost:9121/metrics | grep testkey
```

Thank you!
