### ISSUE TITLE
how to config redis password with illegal characters

### ISSUE THREAD

**Issue by Qin-K** [oliver006/redis_exporter#541]
**Describe the problem**
My redis password has illegal charactors but I don't konw how to config it corrently

**What version of redis_exporter are you running?**
 `redis_exporter --version`
v1.26.0

**Running the exporter**

Firstly, my prometheus.yml as follow， `^...` is my redis password

```
  - job_name: 'redis_exporter_targets'
    static_configs:
      - targets:
        - redis://:^...@10.228.131.2:6379
    metrics_path: /scrape
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9121

  ## config for scraping the exporter itself
  - job_name: 'redis_exporter'
    static_configs:
      - targets:
        - localhost:9121
```

And I use the following command run redis_exporter

```
./redis_exporter --redis.addr=
```

I found the state of `redis_exporter_targets` job is DOWN，and error is `server returned HTTP status 400 Bad Request`

I guess the redis scheme configed in prometheus maybe incorrently because it has the url illegal characters. so I encode my redis password and try again，`%5E...` is encoded password

```
  - job_name: 'redis_exporter_targets'
    static_configs:
      - targets:
        - redis://:%5E...@10.228.131.2:6379
```

The job state in prometheus change to UP. But unfortunately the auth error messages appear in the console.

```
ERRO[0545] Couldn't set client name, err: NOAUTH Authentication required. 
ERRO[0545] Redis INFO err: NOAUTH Authentication required. 
```

I give up including redis password in a URI，and specify it when run redis_exporter 

```
  - job_name: 'redis_exporter_targets'
    static_configs:
      - targets:
        - redis://10.228.131.2:6379
```

```
./redis_exporter --redis.addr= --redis.password='^...'
```

It seems to be working. But only use one password across the instances in this way, it not meet me because I need config instances which have different passwords. So, is there a way to configure the password with an illegal symbol well.

Sorry for any mistakes. English is not my native language
