### ISSUE TITLE
Cannot run redis-exporter with password from file

### ISSUE THREAD

**Issue by MHoinkaBS** [oliver006/redis_exporter#613]
Hi
Please help with REDIS_PASSWORD_FILE configuration. I guess I'm out of ideas how to do this right now. 

If I run command `-redis.addr redis://test@redis:6379` it's all fine - I can see metrics in Pometheus. 
But when I try to use password file (like in docker-compose below) I get NOAUTH Authentication required. 
It seems from the logs that password is loading properly. 

Out of curiosity I even tried to auth the password in redis-cli (`127.0.0.1:6379> AUTH test`) but it didn't help.  

Unfortunately I need to use password file in my final solution. 

Redis Metrics Exporter v1.35.1
Redis 6.2.6

I'm using following docker-compose for tests:
```
version: "3"
services:
    redis:
     image: redis
     ports:
     - 6379:6379
     command: >
          --requirepass "test"
    redis-exporter:
      image: oliver006/redis_exporter
      command: -redis.addr redis://redis:6379 --debug
      ports:
      - 9121:9121
      environment:
        REDIS_PASSWORD_FILE: /etc/redis-password.json
      volumes:
      - "./redis-password.json:/etc/redis-password.json"
    grafana:
      image: grafana/grafana
      ports:
      - "3000:3000"
    prometheus:
      image: prom/prometheus
      volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
      ports:
      - "9090:9090"
```
redis-password.json
`{"password":"test"}`

Logs: 
```
docker logs redis_redis-exporter_1

time="2022-02-16T16:42:54Z" level=info msg="Redis Metrics Exporter v1.35.1    build date:     sha1: a8f5b9cb192081fea5c95cf07dd5d13edd169389    Go: go1.17.7    GOOS: linux    GOARCH: amd64"
time="2022-02-16T16:42:54Z" level=debug msg="Enabling debug output"
time="2022-02-16T16:42:54Z" level=debug msg="start load password file: /etc/redis-password.json"
time="2022-02-16T16:42:54Z" level=error msg="Loaded 1 entries from /etc/redis-password.json"
time="2022-02-16T16:42:54Z" level=debug msg=password
time="2022-02-16T16:42:54Z" level=debug msg="NewRedisExporter options: exporter.Options{User:\"\", Password:\"\", Namespace:\"redis\", PasswordMap:map[string]string{\"password\":\"test\"}, ConfigCommandName:\"CONFIG\", CheckKeys:\"\", CheckSingleKeys:\"\", CheckStreams:\"\", CheckSingleStreams:\"\", CheckKeysBatchSize:1000, CheckKeyGroups:\"\", MaxDistinctKeyGroups:100, CountKeys:\"\", LuaScript:[]uint8(nil), ClientCertFile:\"\", ClientKeyFile:\"\", CaCertFile:\"\", InclConfigMetrics:false, RedactConfigMetrics:true, InclSystemMetrics:false, SkipTLSVerification:false, SetClientName:true, IsTile38:false, IsCluster:false, ExportClientList:false, ExportClientsInclPort:false, ConnectionTimeouts:15000000000, MetricsPath:\"/metrics\", RedisMetricsOnly:false, PingOnConnect:false, Registry:(*prometheus.Registry)(0xc00006ea00), BuildInfo:exporter.BuildInfo{Version:\"v1.35.1\", CommitSha:\"a8f5b9cb192081fea5c95cf07dd5d13edd169389\", Date:\"\"}}"
time="2022-02-16T16:42:54Z" level=debug msg="parseKeyArg(): Got empty key arguments, parsing skipped"
time="2022-02-16T16:42:54Z" level=debug msg="keys: []exporter.dbKeyPair(nil)"
time="2022-02-16T16:42:54Z" level=debug msg="parseKeyArg(): Got empty key arguments, parsing skipped"
time="2022-02-16T16:42:54Z" level=debug msg="singleKeys: []exporter.dbKeyPair(nil)"
time="2022-02-16T16:42:54Z" level=debug msg="parseKeyArg(): Got empty key arguments, parsing skipped"
time="2022-02-16T16:42:54Z" level=debug msg="streams: []exporter.dbKeyPair(nil)"
time="2022-02-16T16:42:54Z" level=debug msg="parseKeyArg(): Got empty key arguments, parsing skipped"
time="2022-02-16T16:42:54Z" level=debug msg="singleStreams: []exporter.dbKeyPair(nil)"
time="2022-02-16T16:42:54Z" level=debug msg="parseKeyArg(): Got empty key arguments, parsing skipped"
time="2022-02-16T16:42:54Z" level=debug msg="countKeys: []exporter.dbKeyPair(nil)"
time="2022-02-16T16:42:54Z" level=info msg="Providing metrics at :9121/metrics"
time="2022-02-16T16:42:54Z" level=debug msg="Configured redis addr: \"redis://redis:6379\""
time="2022-02-16T16:43:05Z" level=debug msg="Trying DialURL(): redis://redis:6379"
time="2022-02-16T16:43:05Z" level=debug msg="connected to: redis://redis:6379"
time="2022-02-16T16:43:05Z" level=debug msg="connecting took 0.001405 seconds"
time="2022-02-16T16:43:05Z" level=debug msg="c.Do() - running command: CLIENT [SETNAME redis_exporter]"
time="2022-02-16T16:43:05Z" level=debug msg="c.Do() - err: NOAUTH Authentication required."
time="2022-02-16T16:43:05Z" level=debug msg="c.Do() - done"
time="2022-02-16T16:43:05Z" level=error msg="Couldn't set client name, err: NOAUTH Authentication required."
time="2022-02-16T16:43:05Z" level=debug msg="c.Do() - running command: CONFIG [GET *]"
time="2022-02-16T16:43:05Z" level=debug msg="c.Do() - err: NOAUTH Authentication required."
time="2022-02-16T16:43:05Z" level=debug msg="c.Do() - done"
time="2022-02-16T16:43:05Z" level=debug msg="Redis CONFIG err: NOAUTH Authentication required."
time="2022-02-16T16:43:05Z" level=debug msg="c.Do() - running command: INFO [ALL]"
time="2022-02-16T16:43:05Z" level=debug msg="c.Do() - err: NOAUTH Authentication required."
time="2022-02-16T16:43:05Z" level=debug msg="c.Do() - done"
time="2022-02-16T16:43:05Z" level=debug msg="Redis INFO ALL err: NOAUTH Authentication required."
time="2022-02-16T16:43:05Z" level=debug msg="c.Do() - running command: INFO []"
time="2022-02-16T16:43:05Z" level=debug msg="c.Do() - err: NOAUTH Authentication required."
time="2022-02-16T16:43:05Z" level=debug msg="c.Do() - done"
time="2022-02-16T16:43:05Z" level=error msg="Redis INFO err: NOAUTH Authentication required."
time="2022-02-16T16:43:05Z" level=debug msg="scrapeRedisHost() done"
```
