### ISSUE TITLE
How to use multi redis instances but show their hostname (or any given name) instead of ip ?

### ISSUE THREAD

**Issue by khurshid-alam** [oliver006/redis_exporter#623]
**Describe the problem**
Our redis config is 

```yml
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
rule_files:
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "d-redis"
    static_configs:
            - targets: ["redis://168.x.x.x:17539","redis://169.x.x.x:17539","redis://49.x.x.x:17539","redis://167.x.x.x:17539","redis://157.x.x.x:17539","redis://154.x.x.x:17539","redis://94.x.x.x:17539","redis://94.130.x.x:17539","redis://142.132.x.x:17539"]
    metrics_path: /scrape
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 172.17.0.6:9121
  - job_name: 'redis_exporter'
    static_configs:
      - targets:
        - 172.17.0.6:9121
```

So in grafana it shows up as **redis://x.x.x.x**. What I need is to view them as lebel for each instance, For example **hub-01, hub-02, hub-03**.

I beleive this can achieved by modifyting prometheus config. Please suggests how to do that

**What version of redis_exporter are you running?**
We are using in-built gitlab ce redis exporter (gitlab version 14.9)

**Running the exporter**
gitlabctl reconfigure

**Screenshots**
If applicable, add screenshots to help explain your question.

**Additional context**
Add any other context about the question here.
