### ISSUE TITLE
prometheus.yml file

### ISSUE THREAD

**Issue by stobbe99** [oliver006/redis_exporter#639]
Hello,

I notice confusion about prometheus.yml file and this redis_exporter.

IThe prometheus.yml is a config file used for prometheus to tell him where the end-points to be scraped can be found.

If you want the redis_exporter to scrape multiple redis instances, you have to start multiple instances of the redis_exporter pointing to the correct redis instance.

Can someone confirm (-;

KR Henk

**Comment by oliver006** [comment]
Yeah, scraping multiple Redis instances with one redis_exporter can be confusing.

To scrape multiple Redis instances with one exporter, you run one redis_exporter and then configure the Prometheus server (via the prometheus.yml file) to hit the exporter for each of the targets you want to scrape. In that way you don't have to run multiple exporters.

You obviously can run multiple instances of the exporter, configure each for a different Redis instance and then scrape all the exporters (that's easily done in a k8s setup where you run the exporter as a sidecar to the redis container) but can be trickier/more wasteful in other scenarios.

If you have suggestions on how to improve the docs then let me know.

**Comment by neomantra** [comment]
See this section of the docs:
https://github.com/oliver006/redis_exporter#prometheus-configuration-to-scrape-multiple-redis-hosts

What confused me at first, and perhaps confuses OP, is that users can directly configure the `redis-exporter` to scrape a single specific Redis instance through command-line flags.   So I was doing that multiple on multiple instances

 I was new to Prometheus Exporters in general, so I didn't realize that `redis-exporter` would receive scrape URLs from the Prometheus Server.

But now I know better -- this is an excerpt of my `prometheus.yml` for scraping multiple Redis instances... one stanza is for a static list from a file and the other is from Consul.  It's similar to the documentation linked above.

```
# Redis Exporter static jobs
- job_name: 'redis_exporter_targets'
  file_sd_configs:
    - files:
      - /etc/prometheus/exporters/redis-targets.yml
  metrics_path: /scrape
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance

# Redis Exporter consul jobs
- job_name: 'redis_exporter_consul_targets'
  consul_sd_configs:
  - server: '127.0.0.1:8500'
    scheme: http
    tags: ['redis']
  metrics_path: /scrape
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - source_labels: [__meta_consul_service]
      target_label: service
    - source_labels: [__meta_consul_dc]
      target_label: dc
```

```
# redis-targets.yml
- targets:
  - redis://server1:6379
  - redis://server2:42069
```
