### ISSUE TITLE
Connection to Redis responds with : SSL routines:ssl3_get_record:wrong version number

### ISSUE THREAD

**Issue by DGRFL** [oliver006/redis_exporter#711]
I try to connect a Redis Exporter to a Redis cluster (RHEL, not containerized)
Redis Exporter v1.44.0    build date: 2022-08-25-05:21:38
Redis Server 6.2.6

The redis server was started (currently still as as root user) 
```
sudo /apps/redis/bin/redis-server /apps/redis/7000/redis.conf 
	--tls-port 7000 
	--port 0     
	--tls-cert-file /apps/redis/ca/redis.crt     
	--tls-key-file /apps/redis/ca/redis.key     
	--tls-ca-cert-file /apps/redis/ca/ca.crt

```
Redis-cli towards the Redis instance works fine with the following arguments
```
/apps/redis/bin/redis-cli 
   -h 10.244.226.94 
   -p 7001 
   --tls 
   --cert /apps/redis/ca/redis.crt 
   --key /apps/redis/ca/redis.key 
   --cacert /apps/redis/ca/ca.crt ping
```

However when running the redis-exporter with following arguments, I get an exception

```
./redis_exporter 
	--redis.addr= 
	-debug 
	--skip-tls-verification=true 
	--tls-ca-cert-file=/apps/redis/ca/ca.crt --tls-client-key-file=/apps/redis/ca/redis.key --tls-client-cert-file=/apps/redis/ca/redis.crt 
	--set-client-name=false

```
```

INFO[0000] Redis Metrics Exporter v1.44.0    build date: 2022-08-25-05:21:38    sha1: 19f7b036bb46869858eec74d8d3fc2186d641399    Go: go1.19    GOOS: linux    GOARCH: amd64
DEBU[0000] Enabling debug output
DEBU[0000] NewRedisExporter options: exporter.Options{User:"", Password:"", Namespace:"redis", PasswordMap:map[string]string{}, ConfigCommandName:"CONFIG", CheckKeys:"", CheckSingleKeys:"", CheckStreams:"", CheckSingleStreams:"", CheckKeysBatchSize:1000, CheckKeyGroups:"", MaxDistinctKeyGroups:100, CountKeys:"", LuaScript:[]uint8(nil), ClientCertFile:"/apps/redis/ca/redis.crt", ClientKeyFile:"/apps/redis/ca/redis.key", CaCertFile:"/apps/redis/ca/ca.crt", InclConfigMetrics:false, RedactConfigMetrics:true, InclSystemMetrics:false, SkipTLSVerification:true, SetClientName:false, IsTile38:false, IsCluster:false, ExportClientList:false, ExportClientsInclPort:false, ConnectionTimeouts:15000000000, MetricsPath:"/metrics", RedisMetricsOnly:false, PingOnConnect:false, Registry:(*prometheus.Registry)(0xc0000769b0), BuildInfo:exporter.BuildInfo{Version:"v1.44.0", CommitSha:"19f7b036bb46869858eec74d8d3fc2186d641399", Date:"2022-08-25-05:21:38"}}
DEBU[0000] parseKeyArg(): Got empty key arguments, parsing skipped
DEBU[0000] keys: []exporter.dbKeyPair(nil)
DEBU[0000] parseKeyArg(): Got empty key arguments, parsing skipped
DEBU[0000] singleKeys: []exporter.dbKeyPair(nil)
DEBU[0000] parseKeyArg(): Got empty key arguments, parsing skipped
DEBU[0000] streams: []exporter.dbKeyPair(nil)
DEBU[0000] parseKeyArg(): Got empty key arguments, parsing skipped
DEBU[0000] singleStreams: []exporter.dbKeyPair(nil)
DEBU[0000] parseKeyArg(): Got empty key arguments, parsing skipped
DEBU[0000] countKeys: []exporter.dbKeyPair(nil)
DEBU[0000] Load key pair: /apps/redis/ca/redis.crt /apps/redis/ca/redis.key
DEBU[0000] Load CA cert file: /apps/redis/ca/ca.crt
INFO[0000] Providing metrics at :9121/metrics
DEBU[0000] Configured redis addr: ""
DEBU[0013] NewRedisExporter options: exporter.Options{User:"", Password:"", Namespace:"redis", PasswordMap:map[string]string{}, ConfigCommandName:"CONFIG", CheckKeys:"", CheckSingleKeys:"", CheckStreams:"", CheckSingleStreams:"", CheckKeysBatchSize:1000, CheckKeyGroups:"", MaxDistinctKeyGroups:100, CountKeys:"", LuaScript:[]uint8(nil), ClientCertFile:"/apps/redis/ca/redis.crt", ClientKeyFile:"/apps/redis/ca/redis.key", CaCertFile:"/apps/redis/ca/ca.crt", InclConfigMetrics:false, RedactConfigMetrics:true, InclSystemMetrics:false, SkipTLSVerification:true, SetClientName:false, IsTile38:false, IsCluster:false, ExportClientList:false, ExportClientsInclPort:false, ConnectionTimeouts:15000000000, MetricsPath:"/metrics", RedisMetricsOnly:false, PingOnConnect:false, Registry:(*prometheus.Registry)(0xc000220410), BuildInfo:exporter.BuildInfo{Version:"v1.44.0", CommitSha:"19f7b036bb46869858eec74d8d3fc2186d641399", Date:"2022-08-25-05:21:38"}}
DEBU[0013] parseKeyArg(): Got empty key arguments, parsing skipped
DEBU[0013] keys: []exporter.dbKeyPair(nil)
DEBU[0013] parseKeyArg(): Got empty key arguments, parsing skipped
DEBU[0013] singleKeys: []exporter.dbKeyPair(nil)
DEBU[0013] parseKeyArg(): Got empty key arguments, parsing skipped
DEBU[0013] streams: []exporter.dbKeyPair(nil)
DEBU[0013] parseKeyArg(): Got empty key arguments, parsing skipped
DEBU[0013] singleStreams: []exporter.dbKeyPair(nil)
DEBU[0013] parseKeyArg(): Got empty key arguments, parsing skipped
DEBU[0013] countKeys: []exporter.dbKeyPair(nil)
DEBU[0013] Load key pair: /apps/redis/ca/redis.crt /apps/redis/ca/redis.key
DEBU[0013] Load CA cert file: /apps/redis/ca/ca.crt
DEBU[0013] Trying DialURL(): redis://git-kfkrds01:7000
DEBU[0013] connected to: redis://git-kfkrds01:7000
DEBU[0013] connecting took 0.003200 seconds
DEBU[0013] c.Do() - running command: CONFIG [GET *]
DEBU[0013] c.Do() - err: read tcp 10.244.226.93:47516->10.244.226.93:7000: read: connection reset by peer
DEBU[0013] c.Do() - done
DEBU[0013] Redis CONFIG err: read tcp 10.244.226.93:47516->10.244.226.93:7000: read: connection reset by peer
DEBU[0013] c.Do() - running command: INFO [ALL]
DEBU[0013] c.Do() - err: set tcp 10.244.226.93:47516: use of closed network connection
DEBU[0013] c.Do() - done
DEBU[0013] Redis INFO ALL err: set tcp 10.244.226.93:47516: use of closed network connection
DEBU[0013] c.Do() - running command: INFO []
DEBU[0013] c.Do() - err: set tcp 10.244.226.93:47516: use of closed network connection
DEBU[0013] c.Do() - done
ERRO[0013] Redis INFO err: set tcp 10.244.226.93:47516: use of closed network connection
DEBU[0013] scrapeRedisHost() done
DEBU[0028] NewRedisExporter options: exporter.Options{User:"", Password:"", Namespace:"redis", PasswordMap:map[string]string{}, ConfigCommandName:"CONFIG", CheckKeys:"", CheckSingleKeys:"", CheckStreams:"", CheckSingleStreams:"", CheckKeysBatchSize:1000, CheckKeyGroups:"", MaxDistinctKeyGroups:100, CountKeys:"", LuaScript:[]uint8(nil), ClientCertFile:"/apps/redis/ca/redis.crt", ClientKeyFile:"/apps/redis/ca/redis.key", CaCertFile:"/apps/redis/ca/ca.crt", InclConfigMetrics:false, RedactConfigMetrics:true, InclSystemMetrics:false, SkipTLSVerification:true, SetClientName:false, IsTile38:false, IsCluster:false, ExportClientList:false, ExportClientsInclPort:false, ConnectionTimeouts:15000000000, MetricsPath:"/metrics", RedisMetricsOnly:false, PingOnConnect:false, Registry:(*prometheus.Registry)(0xc00039e190), BuildInfo:exporter.BuildInfo{Version:"v1.44.0", CommitSha:"19f7b036bb46869858eec74d8d3fc2186d641399", Date:"2022-08-25-05:21:38"}}
DEBU[0028] parseKeyArg(): Got empty key arguments, parsing skipped
DEBU[0028] keys: []exporter.dbKeyPair(nil)
DEBU[0028] parseKeyArg(): Got empty key arguments, parsing skipped
DEBU[0028] singleKeys: []exporter.dbKeyPair(nil)
DEBU[0028] parseKeyArg(): Got empty key arguments, parsing skipped
DEBU[0028] streams: []exporter.dbKeyPair(nil)
DEBU[0028] parseKeyArg(): Got empty key arguments, parsing skipped
DEBU[0028] singleStreams: []exporter.dbKeyPair(nil)
DEBU[0028] parseKeyArg(): Got empty key arguments, parsing skipped
DEBU[0028] countKeys: []exporter.dbKeyPair(nil)
DEBU[0028] Load key pair: /apps/redis/ca/redis.crt /apps/redis/ca/redis.key
DEBU[0028] Load CA cert file: /apps/redis/ca/ca.crt
DEBU[0028] Trying DialURL(): redis://git-kfkrds01:7000
DEBU[0028] connected to: redis://git-kfkrds01:7000
DEBU[0028] connecting took 0.003006 seconds
DEBU[0028] c.Do() - running command: CONFIG [GET *]
DEBU[0028] c.Do() - err: read tcp 10.244.226.93:46322->10.244.226.93:7000: read: connection reset by peer
DEBU[0028] c.Do() - done
DEBU[0028] Redis CONFIG err: read tcp 10.244.226.93:46322->10.244.226.93:7000: read: connection reset by peer
DEBU[0028] c.Do() - running command: INFO [ALL]
DEBU[0028] c.Do() - err: set tcp 10.244.226.93:46322: use of closed network connection
DEBU[0028] c.Do() - done
DEBU[0028] Redis INFO ALL err: set tcp 10.244.226.93:46322: use of closed network connection
DEBU[0028] c.Do() - running command: INFO []
DEBU[0028] c.Do() - err: set tcp 10.244.226.93:46322: use of closed network connection
DEBU[0028] c.Do() - done
ERRO[0028] Redis INFO err: set tcp 10.244.226.93:46322: use of closed network connection
DEBU[0028] scrapeRedisHost() done

```

THe redis server log contains
```

2677382:S 26 Oct 2022 11:42:24.338 # Error accepting a client connection: error:1408F10B:SSL routines:ssl3_get_record:wrong version number
2677382:S 26 Oct 2022 11:42:39.337 # Error accepting a client connection: error:1408F10B:SSL routines:ssl3_get_record:wrong version number
```

The redis logfile contains
```
3371192:C 26 Oct 2022 11:53:50.099 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
3371192:C 26 Oct 2022 11:53:50.099 # Redis version=6.2.6, bits=64, commit=00000000, modified=0, pid=3371192, just started
3371192:C 26 Oct 2022 11:53:50.099 # Configuration loaded
3371192:M 26 Oct 2022 11:53:50.103 * Increased maximum number of open files to 10032 (it was originally set to 1024).
3371192:M 26 Oct 2022 11:53:50.104 * monotonic clock: POSIX clock_gettime
3371192:M 26 Oct 2022 11:53:50.106 * Node configuration loaded, I'm 45cc18c6f0fdf89ce7eeeea4223dead8cea30b6d
3371192:M 26 Oct 2022 11:53:50.107 * Running mode=cluster, port=7000.
3371192:M 26 Oct 2022 11:53:50.107 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
3371192:M 26 Oct 2022 11:53:50.107 # Server initialized
3371192:M 26 Oct 2022 11:53:50.107 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
3371192:M 26 Oct 2022 11:53:50.109 * Reading RDB preamble from AOF file...
3371192:M 26 Oct 2022 11:53:50.109 * Loading RDB produced by version 6.2.6

....

3371192:S 26 Oct 2022 11:54:59.348 - Accepted 10.244.226.93:38796
3371192:S 26 Oct 2022 11:54:59.348 # Error accepting a client connection: error:1408F10B:SSL routines:ssl3_get_record:wrong version number (conn: fd=16)

```

The most important redis.conf settings are : 
```

################################## NETWORK #####################################

bind 10.244.226.93
#port 7000

tcp-backlog 511
timeout 0
tcp-keepalive 300

################################# TLS/SSL #####################################

port 0
tls-port 7000

tls-cert-file /apps/redis/ca/redis.crt
tls-key-file /apps/redis/ca/redis.key

tls-dh-params-file /apps/redis/ca/redis.dh
tls-ca-cert-file /apps/redis/ca/ca.crt

tls-auth-clients no
tls-replication yes
tls-cluster yes

tls-protocols "TLSv1.2 TLSv1.3"

tls-ciphersuites TLS_CHACHA20_POLY1305_SHA256

```

In Prometheus.yml, following targets are specified.
I tested with and without the insecure_skip_verify clause.
```

# --- REDIS in Prometheus.yml --------

  - job_name: 'redis_exporter_targets'
    static_configs:
      - targets:
        - redis://git-kfkrds01:7000
        #- redis://git-kfkrds01:7001
        #- redis://git-kfkrds02:7000
        #- redis://git-kfkrds02:7001
        #- redis://git-kfkrds03:7000
        #- redis://git-kfkrds03:7001
    metrics_path: /scrape
    scheme: http
    #tls_config:
      #insecure_skip_verify: true
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: git-kfkrds01:9121

  ## config for scraping the exporter itself
  - job_name: 'redis_exporter'
    static_configs:
      - targets:
        - git-kfkrds01:9121


# --- End of REDIS --------

```

**Comment by oliver006** [comment]
This might be the same as #703

**Comment by bjosv** [comment]
I've seen `Error accepting a client connection: error:1408F10B:SSL routines:ssl3_get_record:wrong version number` with another client and I believe it's an indication of that the Redis server accepts TLS, but the client is not configured to use TLS.

Would it work if you configure `rediss://git-kfkrds01:7000` instead of `redis://git-kfkrds01:7000` in prometheus?

**Comment by DGRFL** [comment]
Indeed it works....
THe redis server log file still shows the same error : "Error accepting a client connection: error:1408F10B:SSL routines:ssl3_get_record:wrong version number (conn: fd=17)".
But the redis-exporter receives the metrics, and can push them to prometheus.  I assume the skip 

Just for reference (if anybody has same issue):
prometheus.yml

```
  - job_name: 'redis_exporter_targets'
    static_configs:
      - targets:
        - rediss://git-kfkrds01:7000
    metrics_path: /scrape
    scheme: http
    tls_config:
      insecure_skip_verify: true
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: git-kfkrds01:9121

  ## config for scraping the exporter itself
  - job_name: 'redis_exporter'
    static_configs:
      - targets:
        - git-kfkrds01:9121

```
Startup of the redis-exporter

```
./redis_exporter --redis.addr= -debug --skip-tls-verification=true --tls-ca-cert-file=/apps/redis/ca/ca.crt --tls-client-key-file=/apps/redis/ca/redis.key --tls-client-cert-file=/apps/redis/ca/redis.crt --set-client-name=true --is-cluster=true
```
Thanks a lot....
