### ISSUE TITLE
Redis exporter doesn't expose redis-cli info to prometheus metrics 

### ISSUE THREAD

**Issue by Fadih** [oliver006/redis_exporter#89]
hi my friend ,

i need your help to expose redis-cli info to /metrics in redis exporter so the grafana dashboard can collect them

thanks

**Comment by fragtom** [comment]
Same for me, I couldn't find any solution, to receive specific keys here.. Had you already success? 

In my case, only some info e.g. ```redis_up``` is available.. not more.. 

```
redis_up{addr="prod.redis",endpoint="http-metrics",instance="172.31.19.191:9121",job="redis-exporter",namespace="monitoring",pod="redis-exporter-2724175770-gtzsg",service="redis-exporter"}
```

**Comment by Fadih** [comment]
no it's not working for me ,im using this grafana templates https://github.com/oliver006/redis_exporter/tree/master/contrib
and it's failed to pull all the metrics from the template

**Comment by oliver006** [comment]
Using this minimal docker-compose file:
```
version: '2'

services:
  redis-server:
    image: redis:3.2.10
    ports:
      - 6379:6379

  redis-exporter:
    image: oliver006/redis_exporter:v0.11.3
    ports:
      - 9121:9121
    entrypoint: /bin/redis_exporter -redis.addr redis://redis-server:6379
```
First, `docker-compose up`

If you now run `curl -s localhost:9121/metrics | grep redis_`

I see all the `redis_` metrics as expected.

How are you running / configuring the redis_exporter ?
