### ISSUE TITLE
Documentation regarding accepted parameters for exporter

### ISSUE THREAD

**Issue by matiasba** [oliver006/redis_exporter#928]
There seems to be at least 5 target parameters that are not documented properly.
```
check-keys
check-single-keys
check-streams
check-single-streams
count-keys
```
[The parameters are parsed here](https://github.com/oliver006/redis_exporter/blob/46d980e85b7b7b934a9157f24bc9eeeda4290af1/exporter/http.go#L58-L77)

They can be used like this:
```
scrape_configs:
  - job_name: 'redis_exporter'
    scheme: https
    static_configs:
      - targets:
        - redis://first-redis-host:6379
    metrics_path: /scrape
    params:
      check-keys: ["mt:*,la:*"]
      count-keys: ["mt:*,la:*"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: <<REDIS-EXPORTER-HOSTNAME>>:9121
```
It seems the parameters need to be pass as a single string separated by commas instead of a proper yaml array. If passed as an array only the last value is used.
