### ISSUE TITLE
redis-exporter container restarted with 137(OOMKilled)

### ISSUE THREAD

**Issue by SarthakSahu** [oliver006/redis_exporter#929]
**Describe the problem**
We are using the docker image in K8S env. Prometheus has not configured to scrape the metrics.
The memory consumption is keep on increasing steadily and container is getting restarted with OOMKilled in 7-10 days roughly.

Below is the resource configuration. 
```
        resources:
          limits:
            cpu: 250m
            ephemeral-storage: 64Mi
            memory: 64Mi
          requests:
            cpu: 250m
            ephemeral-storage: 64Mi
            memory: 64Mi
```

**What version of redis_exporter are you running?**
Please run `redis_exporter --version` if you're not sure what version you're running.
v1.59.0

**Running the exporter**
Docker is getting used.

**Expected behavior**
redis_exporter should not kill by OOm.

**Screenshots**

**Additional context**
